# Generated by Django 5.0.6 on 2024-06-04 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_buku', models.CharField(max_length=100)),
                ('jenis_buku', models.TextField()),
                ('penerbit', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='peminjam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_peminjam', models.CharField(max_length=100)),
                ('buku', models.TextField()),
                ('jumlah', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='pustakawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pengembalian', models.CharField(max_length=100)),
                ('judul', models.TextField()),
                ('pengarang', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('peminjam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pustakawan', to='api.peminjam')),
            ],
        ),
        migrations.DeleteModel(
            name='blogpost',
        ),
    ]
