# Generated by Django 5.0.6 on 2024-06-05 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_buku_peminjam_pustakawan_delete_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peminjam',
            old_name='buku',
            new_name='riwayat',
        ),
        migrations.RenameField(
            model_name='peminjam',
            old_name='jumlah',
            new_name='transaksi',
        ),
        migrations.RenameField(
            model_name='pustakawan',
            old_name='judul',
            new_name='nama_buku',
        ),
        migrations.RenameField(
            model_name='pustakawan',
            old_name='pengarang',
            new_name='pembelian',
        ),
        migrations.RenameField(
            model_name='pustakawan',
            old_name='tanggal_pengembalian',
            new_name='pengembalian',
        ),
    ]
